/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as PublicTonconnectManifestDotjsonRouteImport } from "./routes/_public/tonconnect-manifest[.]json";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const PublicTonconnectManifestDotjsonRoute = PublicTonconnectManifestDotjsonRouteImport.update({
  id: "/_public/tonconnect-manifest.json",
  path: "/tonconnect-manifest.json",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/tonconnect-manifest.json": typeof PublicTonconnectManifestDotjsonRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/tonconnect-manifest.json": typeof PublicTonconnectManifestDotjsonRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_public/tonconnect-manifest.json": typeof PublicTonconnectManifestDotjsonRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/tonconnect-manifest.json";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/tonconnect-manifest.json";
  id: "__root__" | "/" | "/_public/tonconnect-manifest.json";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  PublicTonconnectManifestDotjsonRoute: typeof PublicTonconnectManifestDotjsonRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_public/tonconnect-manifest.json": {
      id: "/_public/tonconnect-manifest.json";
      path: "/tonconnect-manifest.json";
      fullPath: "/tonconnect-manifest.json";
      preLoaderRoute: typeof PublicTonconnectManifestDotjsonRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PublicTonconnectManifestDotjsonRoute: PublicTonconnectManifestDotjsonRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.ts";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
